Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Support.Data;
using Support.Models;

namespace Support.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Companies
        [Authorize(Roles = "Admin")]
        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["PhoneNumberSortParam"] = sortOrder == "pn_asc" ? "pn_desc" : "pn_asc";
            ViewData["DeletedSortParam"] = sortOrder == "deleted" ? "active" : "deleted";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var companies = from c in _context.Companies select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                companies = companies.Where(c => c.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    companies = companies.OrderByDescending(c => c.Name);
                    break;
                case "active":
                    companies = companies.OrderByDescending(c => c.IsDeleted);
                    break;
                case "deleted":
                    companies = companies.OrderBy(c => c.IsDeleted);
                    break;
                case "pn_asc":
                    companies = companies.OrderBy(c => c.PhoneNumber);
                    break;
                case "pn_desc":
                    companies = companies.OrderByDescending(c => c.PhoneNumber);
                    break;
                default:
                    companies = companies.OrderBy(c => c.Name);
                    break;
            }

            int pageSize = 10;
            return View(Utilities.PaginatedList<Company>.Create(companies.AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: Companies/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .SingleOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Address,PhoneNumber")] Company company)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(company);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.SingleOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Address,PhoneNumber,IsDeleted")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .SingleOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Companies.SingleOrDefaultAsync(m => m.Id == id);
            company.IsDeleted = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(int id)
        {
            return _context.Companies.Any(e => e.Id == id);
        }
    }
}

Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Support.Data;
using Support.Models;

namespace Support.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _environment;

        public TicketsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment environment)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
        }


        // GET: Tickets/AllTickets
        [Authorize(Roles = "Admin")]
        public IActionResult AllTickets(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateSortParam"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewData["PrioritySortParam"] = sortOrder == "priority_asc" ? "priority_desc" : "priority_asc";
            ViewData["TypeSortParam"] = sortOrder == "type_asc" ? "type_desc" : "type_asc";
            ViewData["StatusSortParam"] = sortOrder == "status_asc" ? "status_desc" : "status_asc";
            ViewData["NameSortParam"] = sortOrder == "name_asc" ? "name_desc" : "name_asc";
            ViewData["DeletedSortParam"] = sortOrder == "deleted_asc" ? "deleted_desc" : "deleted_asc";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var tickets = from t in _context.Tickets select t;
            tickets = tickets.Include(t => t.TicketType).Include(t => t.Department).ThenInclude(t => t.Company);

            if (!String.IsNullOrEmpty(searchString))
            {
                tickets = tickets.Where(c => c.Subject.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    tickets = tickets.OrderByDescending(c => c.Subject);
                    break;
                case "name_asc":
                    tickets = tickets.OrderBy(c => c.Subject);
                    break;
                case "priority_asc":
                    tickets = tickets.OrderBy(p => p.Priority);
                    break;
                case "priority_desc":
                    tickets = tickets.OrderByDescending(p => p.Priority);
                    break;
                case "status_asc":
                    tickets = tickets.OrderBy(s => s.Status);
                    break;
                case "status_desc":
                    tickets = tickets.OrderByDescending(s => s.Status);
                    break;
                case "type_asc":
                    tickets = tickets.OrderBy(t => t.TicketType);
                    break;
                case "type_desc":
                    tickets = tickets.OrderByDescending(t => t.TicketType);
                    break;
                case "date_desc":
                    tickets = tickets.OrderByDescending(c => c.CreatedAt);
                    break;
                case "deleted_desc":
                    tickets = tickets.OrderByDescending(t => t.IsDeleted);
                    break;
                case "deleted_asc":
                    tickets = tickets.OrderBy(c => c.IsDeleted);
                    break;
                default:
                    tickets = tickets.OrderBy(c => c.CreatedAt);
                    break;
            }

            int pageSize = 10;
            return View(Utilities.PaginatedList<Ticket>.Create(tickets.AsNoTracking(), page ?? 1, pageSize));
        }

        [Authorize(Roles="Admin,CompanyAdmin")]
        public async Task<IActionResult> CompanyTickets(string sortOrder, string currentFilter, string searchString, int? page, int? id)
        {
            Company company = null;
            if (User.IsInRole("Admin") && id != null)
            {
                company = await _context.Companies.SingleOrDefaultAsync(k => k.Id == id);
            }
            else if(User.IsInRole("Admin") && id == null)
            {
                TempData["ErrorMessage"] = "Company id can not be null!";
                return RedirectToAction("Index", "Home");
            }

            var user = await _context.Users.Include(u => u.Company).Include(x => x.Department).SingleOrDefaultAsync(u => u.UserName.Equals(User.Identity.Name));
            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateSortParam"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewData["PrioritySortParam"] = sortOrder == "priority_asc" ? "priority_desc" : "priority_asc";
            ViewData["TypeSortParam"] = sortOrder == "type_asc" ? "type_desc" : "type_asc";
            ViewData["StatusSortParam"] = sortOrder == "status_asc" ? "status_desc" : "status_asc";
            ViewData["NameSortParam"] = sortOrder == "name_asc" ? "name_desc" : "name_asc";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var tickets = from t in _context.Tickets select t;
            if (company == null)
            {
                tickets = tickets.Include(t => t.TicketType).Include(d => d.Department).ThenInclude(c => c.Company).Include(u => u.User).Where(u => u.Department.Company.Id == user.Company.Id);
            }
            else
            {
                tickets = tickets.Include(t => t.TicketType).Include(d => d.Department).ThenInclude(c => c.Company).Include(u => u.User).Where(u => u.Department.Company.Id == company.Id);
            }
            
            if (!String.IsNullOrEmpty(searchString))
            {
                tickets = tickets.Where(c => c.Subject.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    tickets = tickets.OrderByDescending(c => c.Subject);
                    break;
                case "name_asc":
                    tickets = tickets.OrderBy(c => c.Subject);
                    break;
                case "priority_asc":
                    tickets = tickets.OrderBy(p => p.Priority);
                    break;
                case "priority_desc":
                    tickets = tickets.OrderByDescending(p => p.Priority);
                    break;
                case "status_asc":
                    tickets = tickets.OrderBy(s => s.Status);
                    break;
                case "status_desc":
                    tickets = tickets.OrderByDescending(s => s.Status);
                    break;
                case "type_asc":
                    tickets = tickets.OrderBy(t => t.TicketType);
                    break;
                case "type_desc":
                    tickets = tickets.OrderByDescending(t => t.TicketType);
                    break;
                case "date_desc":
                    tickets = tickets.OrderByDescending(c => c.CreatedAt);
                    break;
                default:
                    tickets = tickets.OrderBy(c => c.CreatedAt);
                    break;
            }

            int pageSize = 10;
            return View(Utilities.PaginatedList<Ticket>.Create(tickets.AsNoTracking(), page ?? 1, pageSize));
        }

        [Authorize(Roles="Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> DepartmentTickets(string sortOrder, string currentFilter, string searchString, int? page, int? id)
        {

            Department department = null;
            if ((User.IsInRole("Admin") || User.IsInRole("CompanyAdmin")) && id != null)
            {
                department = await _context.Departments.SingleOrDefaultAsync(k => k.Id == id);
            }
            else if ((User.IsInRole("Admin") || User.IsInRole("CompanyAdmin")) && id == null)
            {
                TempData["ErrorMessage"] = "Department id can not be null!";
                return RedirectToAction("Index", "Home");
            }

            var user = await _context.Users.Include(x => x.Department).SingleOrDefaultAsync(u => u.UserName.Equals(User.Identity.Name));
            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateSortParam"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewData["PrioritySortParam"] = sortOrder == "priority_asc" ? "priority_desc" : "priority_asc";
            ViewData["TypeSortParam"] = sortOrder == "type_asc" ? "type_desc" : "type_asc";
            ViewData["StatusSortParam"] = sortOrder == "status_asc" ? "status_desc" : "status_asc";
            ViewData["NameSortParam"] = sortOrder == "name_asc" ? "name_desc" : "name_asc";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var tickets = from t in _context.Tickets select t;
            if (department == null)
            {
                tickets = tickets.Include(t => t.TicketType).Include(d => d.Department).Include(u => u.User).Where(u => u.Department.Id == user.Department.Id);
            }
            else
            {
                tickets = tickets.Include(t => t.TicketType).Include(d => d.Department).Include(u => u.User).Where(u => u.Department.Id == department.Id);

Views/Shared/_FooterPartial.cshtml
<!-- Footer -->
<footer class="footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item">
                        <a href="#">About</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">Contact</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">Terms of Use</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">Privacy Policy</a>
                    </li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">&copy; Support @DateTime.UtcNow.Year. All Rights Reserved.</p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fab fa-facebook fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fab fa-twitter fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <i class="fab fa-instagram fa-2x fa-fw"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Support</title>
    <link rel="stylesheet" href="~/css/vendor.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="~/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Custom styles for the template -->
    <link href="~/css/landing-page.css" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>
<body>
    <div style="height: 100%; min-height: 100%;" class="topwrapper">
        <nav class="navbar navbar-expand-lg navbar-light shadow bg-default topnav">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Support</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @if (User.IsInRole("Admin") && !User.IsInRole("CompanyAdmin"))
                        {
                            <a class="nav-link" asp-controller="Tickets" asp-action="SelectCompany"><i class="far fa-edit"></i> Submit a Ticket</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Tickets" asp-action="SelectDepartment"><i class="far fa-edit"></i> Submit a Ticket</a>
                        }
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Tickets" asp-action="MyTickets"><i class="far fa-copy"></i> My Tickets</a>
                    </li>
                </ul>
                <div>

                    @if (User.Identity.IsAuthenticated)
                    {

                        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-user"> Account</i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="Manage" asp-action="Index">Settings</a>
                                        <div class="dropdown-divider"></div>
                                        <a href="javascript:void()" onclick="document.getElementById('logoutForm').submit();" class="dropdown-item">Log out</a>
                                    </div>
                                </li>
                            </ul>
                        </form>
                    }
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login"><i class="fas fa-unlock"></i> Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Register"><i class="fas fa-user-plus"></i> Register</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>

        <div id="sidebarwrapper">
            <div class="wrapper">
                @await Html.PartialAsync("_SidebarPartial")
                <div style="background-color: white;" class="container body-content">
                    <div style="background-color: white; padding-top: 1.5rem; min-height: 40rem;" class="container">
                        @if (ViewData["ErrorMessage"] != null)
                        {
                            <div class="alert alert-danger">@ViewData["ErrorMessage"]</div>
                        }
                        else if (TempData["ErrorMessage"] != null)
                        {
                            <div class="alert alert-danger">@TempData["ErrorMessage"]</div>

                        }
                        @if (ViewData["SuccessMessage"] != null)
                        {
                            <div class="alert alert-success">@ViewData["SuccessMessage"]</div>
                        }
                        else if (TempData["SuccessMessage"] != null)
                        {
                            <div class="alert alert-success">@TempData["SuccessMessage"]</div>

                        }
                        @RenderBody()
                    </div>
                    <hr />
                    @await  Html.PartialAsync("_FooterPartial")
                </div>
            </div>
        </div>
    </div>
    <script src="~/js/vendor.min.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>
</html>

Views/Shared/_SidebarPartial.cshtml
<nav id="sidebar" class="active">
    <ul class="list-unstyled components">
        @if (User.Identity.IsAuthenticated)
        {
            @if (User.IsInRole("Admin"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="Stats"><i class="fas fa-chart-bar"></i> Stats</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Tickets" asp-action="AllTickets"><i class="far fa-copy"></i> Tickets</a>
                </li>
            }
            else if (User.IsInRole("CompanyAdmin"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="CompanyStats"><i class="fas fa-chart-bar"></i> Stats</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Tickets" asp-action="CompanyTickets"><i class="far fa-copy"></i> Tickets</a>
                </li>
            }
            else if (User.IsInRole("Personnel"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Tickets" asp-action="DepartmentTickets"><i class="far fa-copy"></i> Tickets</a>
                </li>
            }
        }
        <li>
            @if (User.IsInRole("Admin") || User.IsInRole("CompanyAdmin") || User.IsInRole("Personnel"))
            {
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-briefcase"></i>
                    Manage
                </a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    @if (User.IsInRole("Admin"))
                    {
                        <li>
                            <a asp-controller="Admin" asp-action="Users">Users</a>
                        </li>
                        <li>
                            <a asp-controller="TicketTypes" asp-action="Index">TTypes</a>
                        </li>
                        <li>
                            <a asp-controller="Companies" asp-action="Index">Companies</a>
                        </li>
                    }
                    @if (User.IsInRole("CompanyAdmin") || User.IsInRole("Admin"))
                    {
                        <li>
                            <a asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                    }
                    <li>
                        <a asp-controller="Questions" asp-action="Index">Questions</a>
                    </li>
                    <li>
                        <a asp-controller="QuestionOptions" asp-action="Index">Options</a>
                    </li>
                </ul>
            }
        </li>
        <li>
            <a asp-controller="Home" asp-action="faq">
                <i class="fas fa-question"></i>
                FAQ
            </a>
        </li>
        <li>
            <a asp-controller="Home" asp-action="About">
                <i class="fas fa-briefcase"></i>
                About
            </a>
        </li>
        <li>
            <a asp-controller="Home" asp-action="Contact">
                <i class="fas fa-paper-plane"></i>
                Contact
            </a>
        </li>
    </ul>
    <ul class="list-unstyled components">
        <li>
            <a id="sidebarCollapse" class="btn">
                <i class="fas fa-align-left"></i>
                <span>Toggle</span>
            </a>
        </li>
    </ul>
</nav>