Models/QuestionOption.cs
namespace Support.Models
{
    public class QuestionOption
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Question Question { get; set; }
        public bool IsDeleted { get; set; }
    }
}

Controllers/QuestionOptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Support.Data;
using Support.Models;

namespace Support.Controllers
{
    public class QuestionOptionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public QuestionOptionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: QuestionOptions
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DeletedSortParam"] = sortOrder == "deleted" ? "active" : "deleted";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var questionOptions = from q in _context.QuestionOptions select q;
            questionOptions = questionOptions.Include(x => x.Question).ThenInclude(c => c.Department).ThenInclude(z => z.Company);

            if (User.Identity.IsAuthenticated)
            {
                if ((User.IsInRole("Personnel")) && !User.IsInRole("Admin"))
                {
                    var user = _context.Users.Include(x => x.Company).Include(u => u.Department).SingleOrDefault(u => u.UserName == User.Identity.Name);
                    questionOptions = questionOptions.Where(y => y.Question.Department.Id == user.Department.Id);
                }
                else if (User.IsInRole("CompanyAdmin") && !User.IsInRole("Admin"))
                {
                    var user = _context.Users.Include(x => x.Company).SingleOrDefault(u => u.UserName == User.Identity.Name);
                    questionOptions = questionOptions.Where(t => t.Question.Department.Company.Id == user.Company.Id);
                }
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                questionOptions = questionOptions.Where(t => t.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    questionOptions = questionOptions.OrderByDescending(t => t.Name);
                    break;
                case "active":
                    questionOptions = questionOptions.OrderByDescending(t => t.IsDeleted);
                    break;
                case "deleted":
                    questionOptions = questionOptions.OrderBy(t => t.IsDeleted);
                    break;
                default:
                    questionOptions = questionOptions.OrderBy(t => t.Name);
                    break;
            }

            int pageSize = 10;
            return View(Utilities.PaginatedList<QuestionOption>.Create(questionOptions.AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: QuestionOptions/Details/5
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var questionOption = await _context.QuestionOptions
                .SingleOrDefaultAsync(m => m.Id == id);
            if (questionOption == null)
            {
                return NotFound();
            }

            return View(questionOption);
        }

        // GET: QuestionOptions/Create
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Create(int? id)
        {
            var question = await _context.Questions.Include(q => q.QuestionOptions).SingleOrDefaultAsync(y => y.Id == id);
            if (question == null || !question.QuestionType.Equals("Select"))
            {
                return NotFound();
            }
            ViewBag.question = question;
            return View();
        }

        // POST: QuestionOptions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Create(string Name, int QuestionId)
        {
            if (QuestionId <= 0) { return NotFound(); }
            Question question = await _context.Questions.SingleOrDefaultAsync(q => q.Id == QuestionId);
            if (question == null) { return NotFound(); }
            QuestionOption questionOption = new QuestionOption { Name = Name, Question = question };
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(questionOption);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return View(questionOption);
        }

        // GET: QuestionOptions/Edit/5
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var questionOption = await _context.QuestionOptions.SingleOrDefaultAsync(m => m.Id == id);
            if (questionOption == null)
            {
                return NotFound();
            }
            return View(questionOption);
        }

        // POST: QuestionOptions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,IsDeleted")] QuestionOption questionOption)
        {
            if (id != questionOption.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(questionOption);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionOptionExists(questionOption.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(questionOption);
        }

        // GET: QuestionOptions/Delete/5
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var questionOption = await _context.QuestionOptions
                .SingleOrDefaultAsync(m => m.Id == id);
            if (questionOption == null)
            {
                return NotFound();
            }

            return View(questionOption);
        }

        // POST: QuestionOptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var questionOption = await _context.QuestionOptions.SingleOrDefaultAsync(m => m.Id == id);
            questionOption.IsDeleted = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuestionOptionExists(int id)
        {
            return _context.QuestionOptions.Any(e => e.Id == id);
        }
    }
}

Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Support.Data;
using Support.Models;

namespace Support.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public QuestionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Questions
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["TypeSortParam"] = sortOrder == "type_asc" ? "type_desc" : "type_asc";
            ViewData["DeletedSortParam"] = sortOrder == "deleted" ? "active" : "deleted";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var questions = from q in _context.Questions select q;
            questions = questions.Include(x => x.Department).ThenInclude(c => c.Company).Include(q => q.QuestionOptions);

            if (User.Identity.IsAuthenticated)
            {
                if ((User.IsInRole("Personnel")) && !User.IsInRole("Admin"))
                {
                    var user = _context.Users.Include(x => x.Company).Include(u => u.Department).SingleOrDefault(u => u.UserName == User.Identity.Name);
                    questions = questions.Where(y => y.Department.Id == user.Department.Id);
                }
                else if (User.IsInRole("CompanyAdmin") && !User.IsInRole("Admin"))
                {
                    var user = _context.Users.Include(x => x.Company).SingleOrDefault(u => u.UserName == User.Identity.Name);
                    questions = questions.Where(t => t.Department.Company.Id == user.Company.Id);
                }
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                questions = questions.Where(t => t.QuestionSentence.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    questions = questions.OrderByDescending(t => t.QuestionSentence);
                    break;
                case "active":
                    questions = questions.OrderByDescending(t => t.IsDeleted);
                    break;
                case "deleted":
                    questions = questions.OrderBy(t => t.IsDeleted);
                    break;
                case "type_asc":
                    questions = questions.OrderBy(q => q.QuestionType);
                    break;
                case "type_desc":
                    questions = questions.OrderByDescending(q => q.QuestionType);
                    break;
                default:
                    questions = questions.OrderBy(t => t.QuestionSentence);
                    break;
            }

            int pageSize = 10;
            return View(Utilities.PaginatedList<Question>.Create(questions.AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: Questions/Details/5
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions
                .SingleOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // GET: Questions/Create
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Create(string QuestionSentence, string QuestionType, int DepartmentId)
        {
            var department = _context.Departments.SingleOrDefault(c => c.Id == DepartmentId);
            Question question = new Question { QuestionSentence = QuestionSentence, QuestionType = QuestionType, Department = department };
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(question);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return View(question);
        }

        // GET: Questions/Edit/5
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions.SingleOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,QuestionSentence,QuestionType,IsDeleted")] Question question)
        {
            if (id != question.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(question.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(question);
        }

        // GET: Questions/Delete/5
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions
                .SingleOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,CompanyAdmin,Personnel")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var question = await _context.Questions.SingleOrDefaultAsync(m => m.Id == id);
            question.IsDeleted = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuestionExists(int id)
        {
            return _context.Questions.Any(e => e.Id == id);
        }
    }
}

Views/QuestionOptions/Create.cshtml
@model Support.Models.QuestionOption

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>QuestionOption</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="QuestionId" value="@ViewBag.question.Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Questions" asp-action="Index">Back to List</a>
</div>

Views/QuestionOptions/Delete.cshtml
@model Support.Models.QuestionOption

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QuestionOption</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/QuestionOptions/Details.cshtml
@model Support.Models.QuestionOption

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>QuestionOption</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/QuestionOptions/Edit.cshtml
@model Support.Models.QuestionOption

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>QuestionOption</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/QuestionOptions/Index.cshtml
@model Support.Utilities.PaginatedList<Support.Models.QuestionOption>

@{
    ViewData["Title"] = "Question Options";
}

<h3>Question Options</h3>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-primary" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th class="col-sm-3">
                <a asp-controller="QuestionOptions" asp-action="Index" asp-route-sortOrder="@ViewData["CompanySortParam"]" asp-route-currentFilter="@ViewData["QurrentFilter"]">Company</a>
            </th>
            <th class="col-sm-3">
                <a asp-controller="QuestionOptions" asp-action="Index" asp-route-sortOrder="@ViewData["DepartmentSortParam"]" asp-route-currentFilter="@ViewData["QurrentFilter"]">Department</a>
            </th>
            <th class="col-sm-3">
                <a asp-controller="QuestionOptions" asp-action="Index" asp-route-sortOrder="@ViewData["QuestionSortParam"]" asp-route-currentFilter="@ViewData["QurrentFilter"]">Question</a>
            </th>
            <th class="col-sm-3">
                <a asp-controller="QuestionOptions" asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParam"]" asp-route-currentFilter="@ViewData["QurrentFilter"]">Name</a>
            </th>
            <th class="col-sm-3">
                <a asp-controller="QuestionOptions" asp-action="Index" asp-route-sortOrder="@ViewData["DeletedSortParam"]" asp-route-currentFilter="@ViewData["QurrentFilter"]">Is Deleted</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Question.Department.Company.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Question.Department.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Question.QuestionSentence)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="bottom" title="Edit"><i class="far fa-edit"></i></a>
            </td>
            <td>
                <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="bottom" title="Details"><i class="fas fa-info"></i></a>
            </td>
            <td>
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="bottom" title="Delete"><i class="fas fa-trash-alt"></i></a>
            </td>
        </tr>
        }
    </tbody>
</table>

@if (Model.TotalPages > 1)
{
    @if (Model.HasPreviousPage)
    {
        @if (Model.PageIndex - 1 != 1)
        {
            <a asp-controller="QuestionOptions" asp-action="Index" asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-page="1" asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="btn btn-primary">
                <i class="fas fa-angle-double-left"></i>
            </a>
        }
        <a asp-controller="QuestionOptions" asp-action="Index" asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-page="@(Model.PageIndex - 1)" asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-primary">
            <i class="fas fa-angle-left"></i>
        </a>
    }
    @if (!Model.HasPreviousPage)
    {
        <a class="btn disabled"></a>
    }
    <a style="color:white;" class="btn btn-primary disabled">@Model.PageIndex</a>
    @if (Model.HasNextPage)
    {
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-page="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-primary">
            <i class="fas fa-angle-right"></i>
        </a>
        @if (Model.PageIndex + 1 != Model.TotalPages)
        {
            <a asp-action="Index"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-page="@(Model.TotalPages)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="btn btn-primary">
                <i class="fas fa-angle-double-right"></i>
            </a>
        }
    }
}